image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - nano  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar src/testjava/artifacts/app-mbank.jar &

build_script:
  - ./gradlew test --info